import { CityWeatherData } from "@/types/weather";

export const mockCities: CityWeatherData[] = [
  {
    cityName: "Mandaue City",
    slug: "mandaue",
    lat: 10.3237,
    lon: 123.9227,
    region: "Metro Cebu",
    current: {
      dt: Date.now() / 1000,
      temp: 29,
      feels_like: 39,
      humidity: 78,
      windSpeed: 4.2,
      windDir: "S",
      visibility: 10000,
      uvIndex: 7,
      pressure: 1010,
      sunrise: "06:15 AM",
      sunset: "18:30 PM",
      weather: [{ main: "Clouds", description: "scattered clouds", icon: "🌤" }],
    },
    hourly: Array.from({ length: 24 }, (_, i) => ({
      dt: Date.now() / 1000 + i * 3600,
      temp: 27 + Math.random() * 4,
      pop: Math.random() * 0.6,
      weather: [{ main: "Rain", description: "light rain", icon: "10d" }],
    })),
    daily: Array.from({ length: 7 }, (_, i) => ({
      dt: Date.now() / 1000 + i * 86400,
      temp: { min: 25, max: 31 },
      summary: "Expect a mix of sun and scattered showers throughout the day.",
      weather: [{ main: "Rain", description: "moderate rain", icon: "10d" }],
    })),
    advisory: {
      active: true,
      riskLevel: "moderate",
      summary: "Heavy rainfall expected this afternoon. Possible flooding in low-lying areas.",
    },
  },
  {
    cityName: "Cebu City",
    slug: "cebu-city",
    lat: 10.3157,
    lon: 123.8854,
    region: "Metro Cebu",
    current: {
      dt: Date.now() / 1000,
      temp: 31,
      feels_like: 40,
      humidity: 68,
      windSpeed: 11,
      windDir: "SW",
      visibility: 14,
      uvIndex: 9,
      pressure: 1000,
      sunrise: "06:15 AM",
      sunset: "18:30 PM",
      weather: [{ main: "Clear", description: "clear sky", icon: "☀️" }],
    },
    hourly: Array.from({ length: 24 }, (_, i) => ({
      dt: Date.now() / 1000 + i * 3600,
      temp: 28 + Math.random() * 5,
      pop: Math.random() * 0.2,
      weather: [{ main: "Clear", description: "clear sky", icon: "01d" }],
    })),
    daily: Array.from({ length: 7 }, (_, i) => ({
      dt: Date.now() / 1000 + i * 86400,
      temp: { min: 26, max: 33 },
      summary: "Mostly sunny with light winds throughout the week.",
      weather: [{ main: "Clear", description: "clear sky", icon: "01d" }],
    })),
    advisory: {
      active: false,
      riskLevel: null,
      summary: null,
    },
  },

  // ─────────────────────────────────────────
  // METRO CEBU
  // ─────────────────────────────────────────

  {
    cityName: "Lapu-Lapu City",
    slug: "lapu-lapu",
    lat: 10.3103,
    lon: 123.9494,
    region: "Metro Cebu",
    current: {
      dt: Date.now() / 1000,
      temp: 30,
      feels_like: 38,
      humidity: 72,
      windSpeed: 8.5,
      windDir: "SW",
      visibility: 12000,
      uvIndex: 8,
      pressure: 1008,
      sunrise: "06:15 AM",
      sunset: "18:30 PM",
      weather: [{ main: "Clouds", description: "partly cloudy", icon: "🌤️" }],
    },
    hourly: Array.from({ length: 24 }, (_, i) => ({
      dt: Date.now() / 1000 + i * 3600,
      temp: 28 + Math.random() * 4,
      pop: Math.random() * 0.3,
      weather: [{ main: "Clouds", description: "partly cloudy", icon: "🌤️" }],
    })),
    daily: Array.from({ length: 7 }, (_, i) => ({
      dt: Date.now() / 1000 + i * 86400,
      temp: { min: 26, max: 32 },
      summary: "Partly cloudy with moderate winds throughout the week.",
      weather: [{ main: "Clouds", description: "partly cloudy", icon: "🌤️" }],
    })),
    advisory: {
      active: false,
      riskLevel: null,
      summary: null,
    },
  },
  {
    cityName: "Talisay City",
    slug: "talisay",
    lat: 10.2447,
    lon: 123.8494,
    region: "Metro Cebu",
    current: {
      dt: Date.now() / 1000,
      temp: 30,
      feels_like: 37,
      humidity: 70,
      windSpeed: 6.8,
      windDir: "S",
      visibility: 11000,
      uvIndex: 8,
      pressure: 1009,
      sunrise: "06:15 AM",
      sunset: "18:30 PM",
      weather: [{ main: "Clear", description: "clear sky", icon: "☀️" }],
    },
    hourly: Array.from({ length: 24 }, (_, i) => ({
      dt: Date.now() / 1000 + i * 3600,
      temp: 28 + Math.random() * 4,
      pop: Math.random() * 0.2,
      weather: [{ main: "Clear", description: "clear sky", icon: "☀️" }],
    })),
    daily: Array.from({ length: 7 }, (_, i) => ({
      dt: Date.now() / 1000 + i * 86400,
      temp: { min: 26, max: 33 },
      summary: "Mostly sunny with warm temperatures during the day.",
      weather: [{ main: "Clear", description: "clear sky", icon: "☀️" }],
    })),
    advisory: {
      active: false,
      riskLevel: null,
      summary: null,
    },
  },
  {
    cityName: "Consolacion",
    slug: "consolacion",
    lat: 10.3766,
    lon: 123.957,
    region: "Metro Cebu",
    current: {
      dt: Date.now() / 1000,
      temp: 29,
      feels_like: 36,
      humidity: 79,
      windSpeed: 5.4,
      windDir: "E",
      visibility: 10000,
      uvIndex: 7,
      pressure: 1010,
      sunrise: "06:15 AM",
      sunset: "18:30 PM",
      weather: [{ main: "Clouds", description: "scattered clouds", icon: "🌤️" }],
    },
    hourly: Array.from({ length: 24 }, (_, i) => ({
      dt: Date.now() / 1000 + i * 3600,
      temp: 27 + Math.random() * 4,
      pop: Math.random() * 0.4,
      weather: [{ main: "Clouds", description: "scattered clouds", icon: "🌤️" }],
    })),
    daily: Array.from({ length: 7 }, (_, i) => ({
      dt: Date.now() / 1000 + i * 86400,
      temp: { min: 25, max: 31 },
      summary: "Partly cloudy with occasional afternoon showers.",
      weather: [{ main: "Clouds", description: "scattered clouds", icon: "🌤️" }],
    })),
    advisory: {
      active: false,
      riskLevel: null,
      summary: null,
    },
  },
  {
    cityName: "Lilo-an",
    slug: "liloan",
    lat: 10.3997,
    lon: 123.9992,
    region: "Metro Cebu",
    current: {
      dt: Date.now() / 1000,
      temp: 28,
      feels_like: 35,
      humidity: 82,
      windSpeed: 6.2,
      windDir: "NE",
      visibility: 9000,
      uvIndex: 6,
      pressure: 1011,
      sunrise: "06:14 AM",
      sunset: "18:29 PM",
      weather: [{ main: "Rain", description: "light rain", icon: "🌦️" }],
    },
    hourly: Array.from({ length: 24 }, (_, i) => ({
      dt: Date.now() / 1000 + i * 3600,
      temp: 26 + Math.random() * 4,
      pop: Math.random() * 0.6,
      weather: [{ main: "Rain", description: "light rain", icon: "🌦️" }],
    })),
    daily: Array.from({ length: 7 }, (_, i) => ({
      dt: Date.now() / 1000 + i * 86400,
      temp: { min: 25, max: 30 },
      summary: "Cloudy with occasional light rain throughout the week.",
      weather: [{ main: "Rain", description: "light rain", icon: "🌦️" }],
    })),
    advisory: {
      active: false,
      riskLevel: null,
      summary: null,
    },
  },
  {
    cityName: "Minglanilla",
    slug: "minglanilla",
    lat: 10.2449,
    lon: 123.7966,
    region: "Metro Cebu",
    current: {
      dt: Date.now() / 1000,
      temp: 30,
      feels_like: 38,
      humidity: 74,
      windSpeed: 7.1,
      windDir: "S",
      visibility: 10500,
      uvIndex: 8,
      pressure: 1008,
      sunrise: "06:16 AM",
      sunset: "18:31 PM",
      weather: [{ main: "Clear", description: "clear sky", icon: "☀️" }],
    },
    hourly: Array.from({ length: 24 }, (_, i) => ({
      dt: Date.now() / 1000 + i * 3600,
      temp: 28 + Math.random() * 4,
      pop: Math.random() * 0.25,
      weather: [{ main: "Clear", description: "clear sky", icon: "☀️" }],
    })),
    daily: Array.from({ length: 7 }, (_, i) => ({
      dt: Date.now() / 1000 + i * 86400,
      temp: { min: 26, max: 33 },
      summary: "Mostly sunny and warm with light winds.",
      weather: [{ main: "Clear", description: "clear sky", icon: "☀️" }],
    })),
    advisory: {
      active: false,
      riskLevel: null,
      summary: null,
    },
  },
  {
    cityName: "Cordova",
    slug: "cordova",
    lat: 10.2431,
    lon: 123.9494,
    region: "Metro Cebu",
    current: {
      dt: Date.now() / 1000,
      temp: 29,
      feels_like: 36,
      humidity: 76,
      windSpeed: 9.3,
      windDir: "SW",
      visibility: 12000,
      uvIndex: 8,
      pressure: 1007,
      sunrise: "06:15 AM",
      sunset: "18:30 PM",
      weather: [{ main: "Clouds", description: "broken clouds", icon: "⛅" }],
    },
    hourly: Array.from({ length: 24 }, (_, i) => ({
      dt: Date.now() / 1000 + i * 3600,
      temp: 27 + Math.random() * 4,
      pop: Math.random() * 0.3,
      weather: [{ main: "Clouds", description: "broken clouds", icon: "⛅" }],
    })),
    daily: Array.from({ length: 7 }, (_, i) => ({
      dt: Date.now() / 1000 + i * 86400,
      temp: { min: 26, max: 32 },
      summary: "Partly cloudy with moderate coastal winds.",
      weather: [{ main: "Clouds", description: "broken clouds", icon: "⛅" }],
    })),
    advisory: {
      active: false,
      riskLevel: null,
      summary: null,
    },
  },
  {
    cityName: "San Fernando",
    slug: "san-fernando",
    lat: 10.1625,
    lon: 123.7072,
    region: "Metro Cebu",
    current: {
      dt: Date.now() / 1000,
      temp: 28,
      feels_like: 35,
      humidity: 80,
      windSpeed: 5.8,
      windDir: "SE",
      visibility: 9000,
      uvIndex: 6,
      pressure: 1010,
      sunrise: "06:16 AM",
      sunset: "18:31 PM",
      weather: [{ main: "Rain", description: "light rain", icon: "🌦️" }],
    },
    hourly: Array.from({ length: 24 }, (_, i) => ({
      dt: Date.now() / 1000 + i * 3600,
      temp: 26 + Math.random() * 4,
      pop: Math.random() * 0.6,
      weather: [{ main: "Rain", description: "light rain", icon: "🌦️" }],
    })),
    daily: Array.from({ length: 7 }, (_, i) => ({
      dt: Date.now() / 1000 + i * 86400,
      temp: { min: 25, max: 30 },
      summary: "Occasional rain showers with cloudy periods.",
      weather: [{ main: "Rain", description: "light rain", icon: "🌦️" }],
    })),
    advisory: {
      active: false,
      riskLevel: null,
      summary: null,
    },
  },
  {
    cityName: "Danao City",
    slug: "danao",
    lat: 10.5208,
    lon: 124.0276,
    region: "Metro Cebu",
    current: {
      dt: Date.now() / 1000,
      temp: 28,
      feels_like: 34,
      humidity: 81,
      windSpeed: 5.2,
      windDir: "SE",
      visibility: 9000,
      uvIndex: 6,
      pressure: 1011,
      sunrise: "06:14 AM",
      sunset: "18:29 PM",
      weather: [{ main: "Rain", description: "light rain", icon: "🌧️" }],
    },
    hourly: Array.from({ length: 24 }, (_, i) => ({
      dt: Date.now() / 1000 + i * 3600,
      temp: 26 + Math.random() * 4,
      pop: Math.random() * 0.7,
      weather: [{ main: "Rain", description: "light rain", icon: "🌧️" }],
    })),
    daily: Array.from({ length: 7 }, (_, i) => ({
      dt: Date.now() / 1000 + i * 86400,
      temp: { min: 25, max: 30 },
      summary: "Scattered showers are expected throughout the week.",
      weather: [{ main: "Rain", description: "light rain", icon: "🌧️" }],
    })),
    advisory: {
      active: true,
      riskLevel: "moderate",
      summary: "Periods of heavy rain may occur during the afternoon.",
    },
  },
  {
    cityName: "Carcar City",
    slug: "carcar",
    lat: 10.1061,
    lon: 123.6406,
    region: "Southern Cebu",
    current: {
      dt: Date.now() / 1000,
      temp: 30,
      feels_like: 38,
      humidity: 73,
      windSpeed: 7.3,
      windDir: "SW",
      visibility: 10000,
      uvIndex: 8,
      pressure: 1007,
      sunrise: "06:16 AM",
      sunset: "18:31 PM",
      weather: [{ main: "Clear", description: "clear sky", icon: "☀️" }],
    },
    hourly: Array.from({ length: 24 }, (_, i) => ({
      dt: Date.now() / 1000 + i * 3600,
      temp: 28 + Math.random() * 5,
      pop: Math.random() * 0.25,
      weather: [{ main: "Clear", description: "clear sky", icon: "☀️" }],
    })),
    daily: Array.from({ length: 7 }, (_, i) => ({
      dt: Date.now() / 1000 + i * 86400,
      temp: { min: 26, max: 33 },
      summary: "Warm and mostly sunny conditions are expected.",
      weather: [{ main: "Clear", description: "clear sky", icon: "☀️" }],
    })),
    advisory: {
      active: false,
      riskLevel: null,
      summary: null,
    },
  },
  {
    cityName: "Argao",
    slug: "argao",
    lat: 9.8794,
    lon: 123.605,
    region: "Southern Cebu",
    current: {
      dt: Date.now() / 1000,
      temp: 28,
      feels_like: 35,
      humidity: 82,
      windSpeed: 6.1,
      windDir: "SE",
      visibility: 8500,
      uvIndex: 6,
      pressure: 1011,
      sunrise: "06:17 AM",
      sunset: "18:32 PM",
      weather: [{ main: "Rain", description: "light rain", icon: "🌦️" }],
    },
    hourly: Array.from({ length: 24 }, (_, i) => ({
      dt: Date.now() / 1000 + i * 3600,
      temp: 26 + Math.random() * 4,
      pop: Math.random() * 0.65,
      weather: [{ main: "Rain", description: "light rain", icon: "🌦️" }],
    })),
    daily: Array.from({ length: 7 }, (_, i) => ({
      dt: Date.now() / 1000 + i * 86400,
      temp: { min: 24, max: 30 },
      summary: "Intermittent rain showers are expected during the week.",
      weather: [{ main: "Rain", description: "light rain", icon: "🌦️" }],
    })),
    advisory: {
      active: true,
      riskLevel: "moderate",
      summary: "Localized flooding may occur during periods of heavy rain.",
    },
  },
  {
    cityName: "Sibonga",
    slug: "sibonga",
    lat: 10.0167,
    lon: 123.6167,
    region: "Southern Cebu",
    current: {
      dt: Date.now() / 1000,
      temp: 27,
      feels_like: 34,
      humidity: 85,
      windSpeed: 4.4,
      windDir: "E",
      visibility: 7500,
      uvIndex: 5,
      pressure: 1012,
      sunrise: "06:16 AM",
      sunset: "18:31 PM",
      weather: [{ main: "Clouds", description: "overcast clouds", icon: "☁️" }],
    },
    hourly: Array.from({ length: 24 }, (_, i) => ({
      dt: Date.now() / 1000 + i * 3600,
      temp: 25 + Math.random() * 4,
      pop: Math.random() * 0.55,
      weather: [{ main: "Clouds", description: "overcast clouds", icon: "☁️" }],
    })),
    daily: Array.from({ length: 7 }, (_, i) => ({
      dt: Date.now() / 1000 + i * 86400,
      temp: { min: 24, max: 30 },
      summary: "Overcast skies with scattered showers throughout the week.",
      weather: [{ main: "Clouds", description: "overcast clouds", icon: "☁️" }],
    })),
    advisory: {
      active: false,
      riskLevel: null,
      summary: null,
    },
  },
    {
    cityName: "Bogo City",
    slug: "bogo",
    lat: 11.0517,
    lon: 124.0056,
    region: "Northern Cebu",
    current: {
      dt: Date.now() / 1000,
      temp: 27,
      feels_like: 33,
      humidity: 84,
      windSpeed: 9.1,
      windDir: "NE",
      visibility: 8000,
      uvIndex: 5,
      pressure: 1012,
      sunrise: "06:12 AM",
      sunset: "18:27 PM",
      weather: [{ main: "Rain", description: "moderate rain", icon: "🌧️" }],
    },
    hourly: Array.from({ length: 24 }, (_, i) => ({
      dt: Date.now() / 1000 + i * 3600,
      temp: 25 + Math.random() * 4,
      pop: Math.random() * 0.8,
      weather: [{ main: "Rain", description: "moderate rain", icon: "🌧️" }],
    })),
    daily: Array.from({ length: 7 }, (_, i) => ({
      dt: Date.now() / 1000 + i * 86400,
      temp: { min: 24, max: 30 },
      summary: "Cloudy conditions with occasional moderate rain.",
      weather: [{ main: "Rain", description: "moderate rain", icon: "🌧️" }],
    })),
    advisory: {
      active: true,
      riskLevel: "high",
      summary: "Heavy rainfall and strong winds are possible.",
    },
  },
  {
    cityName: "Daanbantayan",
    slug: "daanbantayan",
    lat: 11.2472,
    lon: 124.0144,
    region: "Northern Cebu",
    current: {
      dt: Date.now() / 1000,
      temp: 28,
      feels_like: 34,
      humidity: 80,
      windSpeed: 10.2,
      windDir: "NE",
      visibility: 9000,
      uvIndex: 6,
      pressure: 1011,
      sunrise: "06:11 AM",
      sunset: "18:26 PM",
      weather: [{ main: "Clouds", description: "broken clouds", icon: "⛅" }],
    },
    hourly: Array.from({ length: 24 }, (_, i) => ({
      dt: Date.now() / 1000 + i * 3600,
      temp: 26 + Math.random() * 4,
      pop: Math.random() * 0.5,
      weather: [{ main: "Clouds", description: "broken clouds", icon: "⛅" }],
    })),
    daily: Array.from({ length: 7 }, (_, i) => ({
      dt: Date.now() / 1000 + i * 86400,
      temp: { min: 25, max: 31 },
      summary: "Partly cloudy with moderate coastal winds.",
      weather: [{ main: "Clouds", description: "broken clouds", icon: "⛅" }],
    })),
    advisory: {
      active: false,
      riskLevel: null,
      summary: null,
    },
  },
  {
    cityName: "Medellin",
    slug: "medellin",
    lat: 10.905,
    lon: 123.963,
    region: "Northern Cebu",
    current: {
      dt: Date.now() / 1000,
      temp: 29,
      feels_like: 36,
      humidity: 77,
      windSpeed: 7.6,
      windDir: "E",
      visibility: 10000,
      uvIndex: 7,
      pressure: 1010,
      sunrise: "06:12 AM",
      sunset: "18:27 PM",
      weather: [{ main: "Clouds", description: "scattered clouds", icon: "🌤️" }],
    },
    hourly: Array.from({ length: 24 }, (_, i) => ({
      dt: Date.now() / 1000 + i * 3600,
      temp: 27 + Math.random() * 4,
      pop: Math.random() * 0.4,
      weather: [{ main: "Clouds", description: "scattered clouds", icon: "🌤️" }],
    })),
    daily: Array.from({ length: 7 }, (_, i) => ({
      dt: Date.now() / 1000 + i * 86400,
      temp: { min: 25, max: 32 },
      summary: "Mostly cloudy with occasional afternoon showers.",
      weather: [{ main: "Clouds", description: "scattered clouds", icon: "🌤️" }],
    })),
    advisory: {
      active: false,
      riskLevel: null,
      summary: null,
    },
  },
];